import csv
import random
import spacy
import re
# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

# Define a list of interview questions along with their ideal answers

interview_questions = [
    ("Tell me about your experience with web development.", "I have worked on several web development projects using HTML, CSS, and JavaScript. I am proficient in front-end frameworks like React and have experience with back-end technologies such as Node.js and Express.", ["web development", "experience", "HTML", "CSS", "JavaScript", "front-end frameworks", "React", "back-end technologies", "Node.js", "Express"]),
    ("What is your approach to building responsive web designs?", "When building responsive web designs, I follow a mobile-first approach. I use CSS media queries and responsive frameworks like Bootstrap to ensure that the website adapts well to different screen sizes and devices.", ["responsive web designs", "CSS media queries", "Bootstrap"]),
    ("How do you optimize a website's performance?", "To optimize a website's performance, I employ techniques like minification and compression of CSS and JavaScript files, caching, and optimizing image sizes. I also analyze the website's performance using tools like Lighthouse or GTmetrix.", ["website performance", "optimization", "minification", "compression", "caching", "image optimization", "Lighthouse", "GTmetrix"]),
    ("Have you worked with any content management systems (CMS)? If so, which ones?", "Yes, I have experience working with popular CMS like WordPress and Drupal. I am familiar with customizing themes, creating custom plugins/modules, and managing content.", ["content management systems", "CMS", "WordPress", "Drupal", "theme customization", "plugin development", "content management"]),
    ("What version control systems are you familiar with?", "I am familiar with Git and have used it extensively for version control in my projects. I am comfortable with common Git operations like branching, merging, and resolving conflicts.", ["version control systems", "Git", "branching", "merging", "conflict resolution"]),
    ("Can you explain the concept of RESTful APIs?", "RESTful APIs (Representational State Transfer) are a set of architectural principles for designing networked applications. They use standard HTTP methods (GET, POST, PUT, DELETE) to perform CRUD (Create, Read, Update, Delete) operations on resources.", ["RESTful APIs", "architectural principles", "HTTP methods", "CRUD operations"]),
    ("Tell me about a challenging project you worked on and how you overcame it.", "In a previous project, I had to optimize the performance of a large e-commerce website. I identified and fixed database query bottlenecks, implemented caching mechanisms, and optimized front-end assets. This resulted in significant improvements in page load times.", ["challenging project", "performance optimization", "database optimization", "caching", "front-end optimization"]),
    ("How do you ensure cross-browser compatibility in your web development projects?", "I perform thorough testing using different browsers like Chrome, Firefox, Safari, and Edge. I use CSS prefixes and polyfills for compatibility with older browsers. I also leverage feature detection techniques and apply progressive enhancement principles.", ["cross-browser compatibility", "testing", "CSS prefixes", "polyfills", "feature detection", "progressive enhancement"]),
    ("Have you used any CSS preprocessors like Sass or Less?", "Yes, I have experience using Sass. I find it helpful for writing modular and maintainable CSS code. I leverage features like variables, nesting, mixins, and functions to improve efficiency and organization in my stylesheets.", ["CSS preprocessors", "Sass", "Less", "variables", "nesting", "mixins", "functions"]),
    ("What is your experience with front-end build tools like webpack or Gulp?", "I have experience working with webpack. It allows me to bundle and optimize my front-end assets, handle dependencies, and apply transformations like transpiling ES6 to ES5 and minifying code.", ["front-end build tools", "webpack", "Gulp", "bundling", "optimization", "transpiling", "minification"]),
    ("Tell me about your familiarity with SQL and database management.", "I have a strong foundation in SQL and have worked with various relational databases such as MySQL and PostgreSQL. I can write complex SQL queries, optimize database performance, and design normalized database schemas.", ["SQL", "database management", "relational databases", "MySQL", "PostgreSQL", "SQL queries", "database performance", "database schema"]),
    ("How do you ensure the security of web applications?", "I follow security best practices such as input validation, parameterized queries, and avoiding common vulnerabilities like SQL injection and cross-site scripting (XSS). I also implement user authentication and authorization mechanisms and use HTTPS for secure communication.", ["web application security", "security best practices", "input validation", "parameterized queries", "SQL injection", "cross-site scripting", "XSS", "user authentication", "authorization", "HTTPS"]),
    ("Tell me about a time when you had to work on a team project.", "In my previous job, I worked on a team project where we developed a collaborative task management application. We followed an Agile methodology, used Git for version control, and communicated regularly through stand-up meetings and collaboration tools like Slack.", ["team project", "Agile methodology", "Git", "version control", "stand-up meetings", "collaboration tools"]),
    ("How do you stay updated with the latest trends and technologies in web development?", "I am an avid learner and regularly keep up with industry blogs, online tutorials, and forums. I attend web development conferences and participate in online communities to share knowledge and learn from others.", ["staying updated", "latest trends", "technologies", "web development", "industry blogs", "online tutorials", "forums", "web development conferences", "online communities"]),
    ("Can you explain the concept of object-oriented programming (OOP)?", "OOP is a programming paradigm that organizes code into objects that encapsulate data and behavior. It promotes concepts like inheritance, polymorphism, and encapsulation, which help improve code reusability, modularity, and maintainability.", ["object-oriented programming", "OOP", "inheritance", "polymorphism", "encapsulation", "code reusability", "modularity", "maintainability"]),
    ("Tell me about a situation where you had to debug a complex issue in your code.", "In a previous project, I encountered a bug that caused inconsistent data rendering in certain scenarios. Through systematic debugging, I identified the root cause as an asynchronous data loading issue. I fixed it by implementing appropriate synchronization techniques.", ["debugging", "complex issue", "bug fixing", "systematic debugging", "root cause", "asynchronous programming", "synchronization"]),
    ("How do you handle tight deadlines and manage your time effectively?", "I am skilled at prioritizing tasks and breaking them down into manageable sub-tasks. I create a timeline, set deadlines for each task, and use productivity tools like project management software or to-do lists. I communicate proactively with stakeholders if I anticipate any challenges in meeting deadlines.", ["tight deadlines", "time management", "task prioritization", "sub-task management", "timeline", "productivity tools", "project management", "stakeholder communication"]),
    ("Tell me about a project where you implemented responsive design principles.", "I worked on a project for a mobile-first e-commerce website. I used a combination of CSS media queries, flexible grids, and fluid layouts to ensure the website looked and functioned well on a variety of devices, from mobile phones to large desktop screens.", ["responsive design principles", "CSS media queries", "flexible grids", "fluid layouts", "mobile-first", "e-commerce website"]),
    ("Do you have experience with performance testing and optimization?", "Yes, I have experience with performance testing tools like JMeter and applying optimization techniques. I analyze performance bottlenecks, optimize database queries, implement caching mechanisms, and leverage techniques like lazy loading and code splitting to improve website performance.", ["performance testing", "optimization techniques", "JMeter", "performance bottlenecks", "database optimization", "caching", "lazy loading", "code splitting"]),
    ("Tell me about your experience with front-end frameworks like Angular or Vue.js.", "I have extensive experience with Vue.js. I have built multiple projects using Vue.js, leveraging its component-based architecture, reactive data-binding, and ecosystem of libraries and plugins. I also have a good understanding of Angular and have worked on Angular projects.", ["front-end frameworks", "Angular", "Vue.js", "component-based architecture", "reactive data-binding"]),
    ("What are some techniques you use to improve website accessibility?", "To improve website accessibility, I follow WCAG (Web Content Accessibility Guidelines) standards. I ensure proper semantic HTML structure, provide alternative text for images, use ARIA roles and attributes, and test with assistive technologies. I also conduct manual audits and use automated accessibility testing tools.", ["website accessibility", "WCAG", "semantic HTML", "alternative text", "ARIA roles", "ARIA attributes", "assistive technologies", "manual audits", "accessibility testing tools"]),
    ("Have you worked with any front-end testing frameworks or libraries like Jest or Cypress?", "Yes, I have experience with Jest and Cypress for front-end testing. I write unit tests to validate individual components' behavior and use end-to-end testing with Cypress to simulate user interactions and ensure proper functionality across the application.", ["front-end testing", "testing frameworks", "Jest", "Cypress", "unit tests", "end-to-end testing", "user interactions"]),
    ("Tell me about your experience with e-commerce integrations and payment gateways.", "I have worked on integrating e-commerce solutions like Shopify and WooCommerce. I have experience with payment gateway APIs such as PayPal and Stripe, handling payment transactions securely, and managing order fulfillment processes.", ["e-commerce integrations", "Shopify", "WooCommerce", "payment gateways", "PayPal", "Stripe", "payment transactions", "order fulfillment"]),
    ("How do you handle browser compatibility issues when working with JavaScript?", "I ensure JavaScript code compatibility by following ECMAScript standards and using feature detection or polyfills for unsupported features. I also test extensively across different browsers and use tools like Babel for transpiling modern JavaScript syntax to ensure compatibility with older browsers.", ["browser compatibility", "JavaScript compatibility", "ECMAScript", "feature detection", "polyfills", "testing", "transpiling"]),
    ("Tell me about your experience with cloud platforms like AWS or Azure.", "I have experience working with AWS (Amazon Web Services) and Azure. I have deployed web applications on AWS EC2 instances, utilized AWS S3 for file storage, and managed databases using AWS RDS. I am familiar with configuring security groups, managing resources, and utilizing platform-specific services.", ["cloud platforms", "AWS", "Azure", "deployment", "EC2", "S3", "RDS", "security groups", "resource management", "platform-specific services"]),
    ("How do you handle and prevent security vulnerabilities like cross-site scripting (XSS) attacks?", "To handle and prevent XSS attacks, I ensure proper input validation and output encoding. I sanitize user inputs, validate and escape dynamic content, and use security libraries like OWASP Java Encoder or DOMPurify. Regular security audits and staying updated with security best practices are also essential.", ["security vulnerabilities", "cross-site scripting", "XSS attacks", "input validation", "output encoding", "sanitization", "validation", "escaping", "security libraries", "OWASP Java Encoder", "DOMPurify"]),
    ("Tell me about your experience with responsive email design and email template development.", "I have experience developing responsive email templates using HTML and CSS. I ensure compatibility across different email clients and devices by using inline styles, media queries, and fallback options. I also utilize tools like Litmus or Email on Acid for testing and previewing email templates.", ["responsive email design", "email template development", "HTML", "CSS", "inline styles", "media queries", "fallback options", "Litmus", "Email on Acid"]),
    ("Have you worked with any task runners or build systems like Grunt or npm scripts?", "Yes, I have worked with Grunt and npm scripts as task runners. I configure tasks for automating processes like file concatenation, minification, and image optimization. I also leverage build systems like Gulp for more complex build pipelines.", ["task runners", "build systems", "Grunt", "npm scripts", "automation", "file concatenation", "minification", "image optimization", "Gulp", "build pipelines"]),
    ("Tell me about your experience with data visualization libraries like D3.js or Chart.js.", "I have experience working with both D3.js and Chart.js for data visualization. I have created interactive charts, graphs, and custom visualizations using these libraries. I am comfortable with data manipulation, rendering, and adding interactivity to visual elements.", ["data visualization", "D3.js", "Chart.js", "interactive charts", "graphs", "custom visualizations", "data manipulation", "rendering", "interactivity"]),
    ("How do you ensure a website's accessibility for users with disabilities?", "To ensure accessibility for users with disabilities, I follow WCAG 2.1 guidelines. I use proper HTML structure, provide alternative text for images, use ARIA attributes, and test with assistive technologies like screen readers. I also consider color contrast, keyboard navigation, and provide captions or transcripts for multimedia content.", ["website accessibility", "WCAG 2.1", "HTML structure", "alternative text", "ARIA attributes", "assistive technologies", "screen readers", "color contrast", "keyboard navigation", "captions", "transcripts"]),
    ("Tell me about a time when you faced a performance bottleneck and how you resolved it.", "In a previous project, we faced a performance bottleneck due to excessive database queries. I optimized the queries by adding appropriate indexes, denormalizing data, and implementing caching mechanisms. This significantly improved the overall performance and reduced response times.", ["performance bottleneck", "database queries", "query optimization", "indexes", "denormalization", "caching", "response times"]),
    ("Have you worked on any internationalization (i18n) or localization (l10n) projects?", "Yes, I have experience with internationalization and localization projects. I have implemented multi-language support using frameworks like React Intl or i18next. I ensure proper handling of text translation, date/time formatting, and currency conversions based on user preferences.", ["internationalization", "i18n", "localization", "l10n", "multi-language support", "React Intl", "i18next", "text translation", "date/time formatting", "currency conversions"]),
    ("Tell me about your experience with version control systems like Git.", "I have extensive experience with Git for version control. I am proficient in using Git commands for branching, merging, committing, and resolving conflicts. I have also utilized Git workflows like Gitflow and GitHub Flow in collaborative projects.", ["version control systems", "Git", "branching", "merging", "committing", "conflict resolution", "Gitflow", "GitHub Flow"]),
    ("How do you ensure the security of user data in web applications?", "I follow security best practices like encrypting sensitive data, using secure protocols (HTTPS), and implementing proper access controls. I also regularly update dependencies, apply security patches, and conduct security audits to identify and address potential vulnerabilities.", ["security of user data", "data encryption", "secure protocols", "HTTPS", "access controls", "dependency updates", "security patches", "security audits", "vulnerability identification"]),
    ("Tell me about a challenging project you worked on and how you overcame obstacles.", "I worked on a project that involved integrating multiple third-party APIs with complex authentication requirements. I faced challenges understanding the API documentation and handling authentication workflows. I overcame these obstacles by thorough research, seeking guidance from API support teams, and implementing test-driven development to ensure correct implementation.", ["challenging project", "third-party APIs", "authentication", "API documentation", "authentication workflows", "research", "API support", "test-driven development"]),
    ("Have you worked with any content management systems (CMS) like WordPress or Drupal?", "Yes, I have experience with content management systems like WordPress and Drupal. I have developed custom themes, implemented custom functionality, and integrated plugins to extend the CMS capabilities. I am familiar with the concepts of content modeling, templating, and managing user permissions within CMS platforms.", ["content management systems", "CMS", "WordPress", "Drupal", "custom themes", "custom functionality", "plugins", "content modeling", "templating", "user permissions"]),
    ("Tell me about your experience with mobile app development using web technologies like React Native.", "I have experience developing mobile apps using React Native. I leverage my web development skills to build cross-platform apps that run on iOS and Android devices. I utilize React Native components, navigation libraries, and access device-specific features using native modules.", ["mobile app development", "web technologies", "React Native", "cross-platform apps", "iOS", "Android", "React Native components", "navigation libraries", "native modules"]),
    ("How do you handle and troubleshoot performance issues in web applications?", "I start by profiling and analyzing the performance using browser developer tools and monitoring tools like Chrome DevTools or New Relic. I identify and optimize slow database queries, reduce network requests, and optimize front-end code. I also leverage caching techniques, compress assets, and utilize performance testing tools.", ["performance issues", "troubleshooting", "profiling", "browser developer tools", "monitoring tools", "Chrome DevTools", "New Relic", "database query optimization", "network optimization", "front-end code optimization", "caching", "asset compression", "performance testing"]),
    ("Tell me about your experience with RESTful APIs and JSON.", "I have extensive experience working with RESTful APIs and JSON. I have built and consumed APIs using frameworks like Express.js or Django REST Framework. I understand REST principles, perform CRUD operations, handle authentication/authorization, and format data using JSON.", ["RESTful APIs", "JSON", "Express.js", "Django REST Framework", "CRUD operations", "authentication", "authorization"]),
    ("Have you worked with any CSS preprocessors like Sass or Less?", "Yes, I have experience with CSS preprocessors like Sass and Less. I use their features like variables, nesting, mixins, and functions to write more maintainable and reusable CSS code. I also utilize their compilation capabilities to generate optimized CSS files.", ["CSS preprocessors", "Sass", "Less", "variables", "nesting", "mixins", "functions", "maintainable code", "reusable code", "compilation"]),
    ("Tell me about your experience with JavaScript frameworks like Angular or React.", "I have worked with both Angular and React. I have developed projects using Angular's component-based architecture, data-binding, and Angular CLI for scaffolding. With React, I have built single-page applications using its virtual DOM, JSX syntax, and state management libraries like Redux.", ["JavaScript frameworks", "Angular", "React", "component-based architecture", "data-binding", "Angular CLI", "single-page applications", "virtual DOM", "JSX syntax", "state management", "Redux"]),
    ("What is your approach to handling cross-browser compatibility issues in web development?", "To handle cross-browser compatibility issues, I test my code across different browsers and versions, including Chrome, Firefox, Safari, and Edge. I utilize CSS prefixes for experimental properties, use feature detection or polyfills for unsupported features, and follow coding standards that ensure broad compatibility.", ["cross-browser compatibility", "testing", "Chrome", "Firefox", "Safari", "Edge", "CSS prefixes", "feature detection", "polyfills", "coding standards"]),
    ("Tell me about your experience with database management systems like MySQL or PostgreSQL.", "I have worked extensively with both MySQL and PostgreSQL. I have designed and optimized database schemas, written complex SQL queries, and utilized database management tools like phpMyAdmin and pgAdmin. I am familiar with indexing, query optimization, and ensuring data integrity.", ["database management systems", "MySQL", "PostgreSQL", "database schema design", "SQL queries", "phpMyAdmin", "pgAdmin", "indexing", "query optimization", "data integrity"]),
    ("Have you worked with any front-end build tools like Webpack or Parcel?", "Yes, I have experience with front-end build tools like Webpack and Parcel. I configure these tools to bundle and optimize JavaScript, CSS, and other assets. I leverage their features like code splitting, tree shaking, and hot module replacement to improve performance and development workflow.", ["front-end build tools", "Webpack", "Parcel", "bundling", "optimization", "code splitting", "tree shaking", "hot module replacement", "performance", "development workflow"]),
    ("Tell me about your experience with Agile software development methodologies.", "I have worked in Agile environments following methodologies like Scrum and Kanban. I have participated in daily stand-ups, sprint planning, and retrospective meetings. I value iterative development, frequent communication, and adaptability to changing requirements.", ["Agile software development", "Scrum", "Kanban", "daily stand-ups", "sprint planning", "retrospective meetings", "iterative development", "communication", "adaptability"]),
    ("What steps do you take to ensure the security of web applications?", "I take several steps to ensure the security of web applications. This includes implementing proper input validation to prevent SQL injection and cross-site scripting (XSS) attacks, using secure protocols like HTTPS, applying authentication and authorization mechanisms, and regularly updating dependencies and applying security patches.", ["security of web applications", "input validation", "SQL injection", "XSS attacks", "secure protocols", "HTTPS", "authentication", "authorization", "dependency updates", "security patches"]),
    ("Tell me about your experience with front-end performance optimization techniques.", "I have experience with front-end performance optimization techniques. I optimize website performance by minifying and compressing CSS and JavaScript files, reducing the number of HTTP requests through file concatenation and image sprites, utilizing browser caching, and lazy-loading resources. I also leverage techniques like code splitting and asynchronous loading to improve initial page load times.", ["front-end performance optimization", "minification", "compression", "HTTP requests", "file concatenation", "image sprites", "browser caching", "lazy-loading", "code splitting", "asynchronous loading", "page load times"]),
    ("Have you worked with any JavaScript testing frameworks like Jest or Mocha?", "Yes, I have worked with JavaScript testing frameworks like Jest and Mocha. I write unit tests, integration tests, and end-to-end tests using these frameworks. I also utilize testing libraries like React Testing Library or Enzyme for testing React components.", ["JavaScript testing frameworks", "Jest", "Mocha", "unit tests", "integration tests", "end-to-end tests", "React Testing Library", "Enzyme"]),
    ("Tell me about your experience with cloud platforms like AWS or Azure.", "I have experience working with both AWS and Azure. I have deployed web applications on AWS EC2 instances and utilized services like S3 for file storage, RDS for database hosting, and CloudFront for content delivery. Similarly, on Azure, I have deployed applications on App Services and utilized services like Blob Storage and Azure SQL Database.", ["cloud platforms", "AWS", "Azure", "web application deployment", "EC2 instances", "S3", "RDS", "CloudFront", "App Services", "Blob Storage", "Azure SQL Database"]),
    ("How do you handle and troubleshoot compatibility issues between different versions of libraries or frameworks?", "To handle compatibility issues between library or framework versions, I ensure proper version management using package managers like npm or Yarn. I carefully review release notes, changelogs, and documentation to identify breaking changes or deprecations. I also leverage tools like Webpack aliases or dependency resolution strategies to resolve conflicts.", ["compatibility issues", "library versions", "framework versions", "version management", "package managers", "npm", "Yarn", "release notes", "changelogs", "documentation", "breaking changes", "deprecations", "Webpack aliases", "dependency resolution"]),
    ("Tell me about your experience with code review processes and collaboration tools.", "I have experience with code review processes using tools like GitHub or Bitbucket. I am familiar with pull requests, reviewing and providing feedback on code changes, and ensuring code quality and adherence to best practices. I also utilize collaboration tools like Slack or Microsoft Teams for effective communication within development teams.", ["code review processes", "GitHub", "Bitbucket", "pull requests", "code feedback", "code quality", "best practices", "collaboration tools", "Slack", "Microsoft Teams"]),
    ("Have you worked with any NoSQL databases like MongoDB or Firebase?", "Yes, I have worked with NoSQL databases like MongoDB and Firebase. I have designed and implemented database schemas, performed CRUD operations, and utilized features like document querying and aggregation. I am also familiar with real-time data synchronization and offline capabilities provided by Firebase.", ["NoSQL databases", "MongoDB", "Firebase", "database schema design", "CRUD operations", "document querying", "aggregation", "real-time data synchronization", "offline capabilities"]),
    ("Tell me about your experience with serverless computing platforms like AWS Lambda or Azure Functions.", "I have experience working with serverless computing platforms like AWS Lambda and Azure Functions. I have written serverless functions in languages like Node.js or Python, configured triggers and event-driven workflows, and utilized serverless databases like AWS DynamoDB or Azure Cosmos DB.", ["serverless computing platforms", "AWS Lambda", "Azure Functions", "serverless functions", "Node.js", "Python", "triggers", "event-driven workflows", "serverless databases", "AWS DynamoDB", "Azure Cosmos DB"]),
    ("How do you ensure the accessibility of web applications for users with disabilities?", "I ensure the accessibility of web applications by following the Web Content Accessibility Guidelines (WCAG). I use semantic HTML, provide alt text for images, ensure proper focus management, and make use of ARIA attributes. I also test my applications using assistive technologies like screen readers and perform manual accessibility audits.", ["accessibility of web applications", "Web Content Accessibility Guidelines", "WCAG", "semantic HTML", "alt text", "focus management", "ARIA attributes", "assistive technologies", "screen readers", "accessibility audits"]),
    ("Tell me about your experience with containerization technologies like Docker or Kubernetes.", "I have experience with containerization technologies like Docker and Kubernetes. I have created Docker containers, written Dockerfiles, and utilized Docker Compose for local development environments. I have also deployed containerized applications on Kubernetes clusters, managed container orchestration, and utilized Kubernetes features like scaling and rolling updates.", ["containerization technologies", "Docker", "Kubernetes", "Docker containers", "Dockerfiles", "Docker Compose", "local development environments", "Kubernetes clusters", "container orchestration", "scaling", "rolling updates"]),
    ("Have you worked with any front-end UI frameworks like Bootstrap or Material-UI?", "Yes, I have experience working with front-end UI frameworks like Bootstrap and Material-UI. I have utilized their pre-built components, grids, and responsive layouts to rapidly prototype and build user interfaces. I also customize their styles and extend their functionality as needed.", ["front-end UI frameworks", "Bootstrap", "Material-UI", "pre-built components", "grids", "responsive layouts", "prototyping", "user interfaces", "customization", "functionality extension"]),
    ("Tell me about your experience with GraphQL and its advantages over REST.", "I have worked with GraphQL and appreciate its advantages over REST. With GraphQL, I can specify the exact data requirements of a query, reducing over-fetching and under-fetching of data. It allows clients to request multiple resources in a single query, resulting in fewer network requests. It also provides a strong typing system and allows clients to evolve their data needs without server changes.", ["GraphQL", "advantages over REST", "data requirements", "over-fetching", "under-fetching", "network requests", "typing system", "data evolution"]),
    ("How do you handle and troubleshoot browser compatibility issues in web development?", "To handle browser compatibility issues, I test my code on different browsers and versions, including Chrome, Firefox, Safari, and Edge. I utilize CSS resets and normalize.css to establish consistent styles across browsers. I also make use of feature detection libraries like Modernizr and polyfills for missing features.", ["browser compatibility issues", "testing", "Chrome", "Firefox", "Safari", "Edge", "CSS resets", "normalize.css", "consistent styles", "feature detection", "Modernizr", "polyfills"]),
    ("Tell me about your experience with UX design principles and usability testing.", "I have a good understanding of UX design principles and have applied them in my projects. I follow principles like simplicity, consistency, and user-centered design. I conduct usability testing sessions to gather user feedback and iterate on designs to improve the user experience.", ["UX design principles", "usability testing", "simplicity", "consistency", "user-centered design", "user feedback", "iteration", "user experience"]),
    ("Have you worked with any back-end frameworks like Django or Ruby on Rails?", "Yes, I have worked with back-end frameworks like Django and Ruby on Rails. I have developed web applications using the MVC pattern, ORM for database interaction, and built RESTful APIs. I also utilize framework-specific features like routing, middleware, and authentication.", ["back-end frameworks", "Django", "Ruby on Rails", "web application development", "MVC pattern", "ORM", "RESTful APIs", "routing", "middleware", "authentication"]),
    ("Tell me about your experience with version control systems like Git.", "I have extensive experience with Git as a version control system. I use Git for tracking changes, creating branches for feature development or bug fixes, and merging branches using pull requests. I am comfortable with Git commands and utilize platforms like GitHub or GitLab for collaborative development.", ["version control systems", "Git", "tracking changes", "branches", "feature development", "bug fixes", "merging", "pull requests", "GitHub", "GitLab"]),
    ("How do you ensure code quality and maintainability in your projects?", "I ensure code quality and maintainability by following coding best practices and design principles. I write clean and modular code, use meaningful variable and function names, and provide comments where necessary. I also perform code reviews, write unit tests, and utilize tools like linters and code formatters to enforce coding standards.", ["code quality", "maintainability", "coding best practices", "design principles", "clean code", "modular code", "variable names", "function names", "comments", "code reviews", "unit tests", "linters", "code formatters", "coding standards"]),
    ("Tell me about your experience with mobile app development using frameworks like React Native or Flutter.", "I have experience with mobile app development using both React Native and Flutter. With React Native, I have built cross-platform mobile apps using JavaScript and React. With Flutter, I have built native apps using Dart. I am familiar with the development process, UI components, and platform-specific integrations.", ["mobile app development", "React Native", "Flutter", "cross-platform mobile apps", "JavaScript", "React", "native apps", "Dart", "development process", "UI components", "platform-specific integrations"]),


]
def calculate_score(answer, keywords):
    score = 0
    for keyword in keywords:
        pattern = r'\b{}\b'.format(keyword)
        if re.search(pattern, answer, re.IGNORECASE):
            score += 1
    return score
# Randomly select 5 questions from the list
random_questions = random.sample(interview_questions, 5)

# Create a CSV file to store the interview data
csv_file = open("interview_data.csv", "w", newline="")
csv_writer = csv.writer(csv_file)
csv_writer.writerow(["Question", "Ideal Answer", "Candidate Answer", "Score", "Keywords Missed"])

# Main interview loop
total_score = 0
for question, ideal_answer, keywords in random_questions:
    bot_question = question
    user_answer = input(bot_question + " ")
    print("Thank you for your answer.")

    # Calculate the similarity score using spaCy
    doc1 = nlp(question)
    doc2 = nlp(user_answer)
    similarity_score = doc1.similarity(doc2)

    # Initialize variables to track keywords and score
    marked_answer = user_answer
    missed_keywords = []
    keyword_score = calculate_score(user_answer, keywords)

    # Provide feedback on missed keywords
    if keyword_score < len(keywords):
        missed_keywords = list(set(keywords) - set(re.findall(r'\b\w+\b', user_answer, re.IGNORECASE)))
        print("You missed the following keywords:", ", ".join(missed_keywords))
    else:
        print("Great job! You covered all the important keywords.")

    # Update the total score with the weighted score
    total_score += (similarity_score * 0.5 + keyword_score)

    # Save the interview data to the CSV file
    csv_writer.writerow([question, ideal_answer, marked_answer, (similarity_score * 0.5 + keyword_score), ", ".join(missed_keywords)])

# Close the CSV file
csv_file.close()

# Calculate the overall score as a percentage
overall_score = (total_score / (len(random_questions) * 5.5)) * 100

# Display the final score
print("Your score in the interview is:", round(overall_score, 2), "% out of 100%.")